apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    app: web
    versao: blue
spec:
  containers:
    - name: web
      image: fabricioveronez/web-color:blue
      ports:
        - name: http
          containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  name: meupod2
  labels:
    app: web
    versao: green
spec:
  containers:
    - name: web
      image: fabricioveronez/web-color:green
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
